"""Regenerate src/data/scanData.js from the current brain record.

Source: the newest ~/Downloads/claude/freesurfer_subjects/EXACT_NUMBERS_<date>.md
(written by ~/freesurfer_subjects/analysis_scripts/exact_numbers_report.py).
Numbers are copied, never retyped. Re-run whenever that report is regenerated:

    python3 scripts/build_scan_data.py
"""
import glob
import json
import os
import re

SRC_DIR = os.path.expanduser("~/Downloads/claude/freesurfer_subjects")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "data", "scanData.js")

src = max(glob.glob(os.path.join(SRC_DIR, "EXACT_NUMBERS_2*.md")), key=os.path.getmtime)
lines = open(src, encoding="utf-8").read().splitlines()


def table_after(heading):
    """Rows (header dropped) of the first markdown table after a line equal to / starting with heading."""
    start = next(i for i, l in enumerate(lines) if l.strip().startswith(heading))
    rows, seen = [], False
    for l in lines[start + 1:]:
        if l.startswith("|"):
            seen = True
            cells = [c.strip() for c in l.strip().strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue
            rows.append(cells)
        elif seen:
            break
    return rows[1:]


def rows_js(rows):
    return "[\n" + "".join("  " + json.dumps(r, ensure_ascii=False) + ",\n" for r in rows) + "]"


updated = re.search(r"Updated (.+?) \(", lines[1]).group(1)
n_aomic = re.search(r"· (\d+) = AOMIC women run through exactly my software", lines[4]).group(1)
n_oasis = re.search(r"· (\d+) = OASIS women run through exactly my software", lines[4]).group(1)

deep = [[r[0], r[1], r[2], r[3]] for r in table_after("1. Whole Brain")]
cortex = []
for band in ("Above Average", "Average", "Below Average"):
    for r in table_after(band):
        cortex.append([r[0], r[1], r[2], r[3], r[5], band.replace(" Average", "").replace("Average", "average").lower()])
cortex.sort(key=lambda r: r[0])
temporal = [r[:5] for r in table_after("Temporal Lobe")]
small = [[r[0], r[1], r[2], r[3]] for r in table_after("4. Thalamus")]

js = f"""// GENERATED by scripts/build_scan_data.py from {os.path.basename(src)} — do not edit by hand.
// Kelsey's 2023 MRI (Siemens 1.5T, post-dye T1 SPACE), age 27, female. Record updated {updated}.
// Percentile = plain size vs healthy women (1 = smaller than almost all, 99 = bigger than almost all),
// no head-size adjustment. Every "L / R" cell is LEFT / RIGHT.
// Groups: 483 = AOMIC women (3T) · 70 = OASIS women (1.5T, matched slice thickness) ·
// {n_oasis} OASIS and {n_aomic} AOMIC women run through exactly the same software as the scan.
// Trust: ✓ high · ~ uncertain / group-dependent · ⚠ border or label effect · ✗ unreliable.

export const RECORD_DATE = {json.dumps(updated)};
export const N_OASIS_SAME = {n_oasis};
export const N_AOMIC_SAME = {n_aomic};

// [structure, 483 women, 70 women, trust]
export const DEEP_VOLUME = {rows_js(deep)};

// [region, 483 women, OASIS same software, AOMIC same software, trust, band]
export const CORTICAL_SURFACE_AREA = {rows_js(cortex)};

// [measure, 483 women, OASIS same software, AOMIC same software, notes]
export const TEMPORAL_LOBE = {rows_js(temporal)};

// [section, OASIS same software, AOMIC same software, notes]
export const SMALL_STRUCTURES = {rows_js(small)};

// volBrain gives no percentiles here — only its own inside/outside-normal verdict,
// and only findings flagged in both of its reports are kept.
export const VOLBRAIN_BOTH_REPORTS = [
  ["Left cerebellar white matter", "below normal"],
  ["Postcentral gyrus (total and left)", "below normal"],
  ["Right superior occipital gyrus", "above normal"],
  ["Cerebellum", "right side bigger"],
  ["Ventral DC", "right side bigger"],
  ["Precentral gyrus, medial segment", "right side bigger"],
];

export const WITHDRAWN = [
  ["Left temporal pole 1st", "border artifact — the tissue at the left tip is above average"],
  ["Left touch / motor / medial orbitofrontal lows", "one comparison group only; average in the other"],
  ["CentileBrain percentiles (24 Sep record)", "replaced by direct comparison with women run through the same software — CentileBrain shifts with scanner + software version"],
  ["Thalamus 99.9th, putamen 0.7th / 3.9th", "August FreeSurfer — the dye made these nuclei look like white matter"],
  ["All cortical thickness percentiles", "not measurable on this scan type"],
  ["All Potvin 2016 percentiles", "fails on healthy controls"],
];
"""
open(OUT, "w", encoding="utf-8").write(js)
print(f"{os.path.basename(src)} ({updated}) → {OUT}: {len(deep)} deep, {len(cortex)} cortex, {len(temporal)} temporal, {len(small)} small")
