#!/usr/bin/env python3
"""Download a fixed set of faces for Who's Who from thispersonnotexist.org.

Every face there is AI-generated (no real person), and the site's terms of use
(https://thispersonnotexist.org/terms-of-use) allow personal and commercial use.
Faces are bundled into the app rather than hotlinked, so the drill doesn't
depend on that site staying up or on its ads/consent scripts.

Writes public/faces/{f,m}NN.jpg (256 px, via macOS `sips`) and
src/data/faces.js. Re-running replaces both.

    python3 scripts/fetch_faces.py            # 30 women + 30 men
    python3 scripts/fetch_faces.py --each 40
"""
import argparse, json, os, subprocess, tempfile, time, urllib.request

SITE = "https://thispersonnotexist.org"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "public", "faces")
INDEX = os.path.join(ROOT, "src", "data", "faces.js")
UA = {"User-Agent": "Mozilla/5.0 (Cortex Console face fetch)"}


def gallery(page):
    req = urllib.request.Request(f"{SITE}/load-gallery", data=json.dumps({"page": page}).encode(),
                                 headers={**UA, "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--each", type=int, default=30, help="faces per sex")
    args = ap.parse_args()

    want = {"F": [], "M": []}
    page = 1
    while any(len(v) < args.each for v in want.values()):
        items = gallery(page)
        if not items:
            break
        for name, it in items.items():
            bucket = want.get(it["typ"])  # skips FB (full body)
            if bucket is not None and len(bucket) < args.each and it["f"] not in bucket:
                bucket.append(it["f"])
        page += 1
        time.sleep(0.5)

    os.makedirs(OUT_DIR, exist_ok=True)
    for f in os.listdir(OUT_DIR):
        os.remove(os.path.join(OUT_DIR, f))
    faces = []
    with tempfile.TemporaryDirectory() as tmp:
        for typ, ids in want.items():
            for i, fid in enumerate(ids, 1):
                raw = os.path.join(tmp, "raw.jpg")
                req = urllib.request.Request(f"{SITE}/downloadimage/{fid}", headers=UA)
                with urllib.request.urlopen(req, timeout=60) as r, open(raw, "wb") as fh:
                    fh.write(r.read())
                name = f"{typ.lower()}{i:02d}.jpg"
                subprocess.run(["sips", "-Z", "256", "-s", "format", "jpeg", "-s", "formatOptions", "72",
                                raw, "--out", os.path.join(OUT_DIR, name)], check=True, capture_output=True)
                faces.append((name, typ))
                print(name)
                time.sleep(0.3)

    with open(INDEX, "w") as fh:
        fh.write("// Generated by scripts/fetch_faces.py — AI-generated faces from thispersonnotexist.org\n")
        fh.write("// (terms allow personal and commercial use). sex: \"F\" | \"M\", used to pick a fitting first name.\n")
        fh.write("export const FACES = [\n")
        for name, typ in faces:
            fh.write(f'  {{ file: "{name}", sex: "{typ}" }},\n')
        fh.write("];\n")
    print(f"{len(faces)} faces → {OUT_DIR}")


if __name__ == "__main__":
    main()
